services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ../../aws_creds:/home/vscode/.aws
      - ../../env_vals:/workspace/env_vals
    working_dir: /workspace
    command: sleep infinity
    expose:
      - "3000" # frontend (next dev)
      - "5000" # backend (express)
      - "5555" # backend_paypal
